name: "hello world workflow"

# when we push to main or prod, run the workflow
on:
  push:
    branches:
      - main
      - prod

# define the jobs to run
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "Hello World"

      - name: "print current date"
        run: date
